version: "3"

services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "3001"
    ports:
      - "3001:8080"
    networks:
      - mern-network

  backend:
    build:
      context: ./server
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
