apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    app: server-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: johnnorlin/demoapp:backend
          ports:
            - containerPort: 8080 #??
